// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7O6ns8CpAC1EhKT7U68ZMBLkrqQNH5C0',
    appId: '1:1068162247377:web:a0e023b5b58be0a412f3f0',
    messagingSenderId: '1068162247377',
    projectId: 'flutter-shop-mds',
    authDomain: 'flutter-shop-mds.firebaseapp.com',
    storageBucket: 'flutter-shop-mds.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs1NOgf6IuG4q6_5BO84atdB3xy4oW4OM',
    appId: '1:1068162247377:android:ed95f84ba277e26412f3f0',
    messagingSenderId: '1068162247377',
    projectId: 'flutter-shop-mds',
    storageBucket: 'flutter-shop-mds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2-YKd4SWEtQ8joE5yJ5qslNpO8NZuow8',
    appId: '1:1068162247377:ios:b80c970350dd8f9612f3f0',
    messagingSenderId: '1068162247377',
    projectId: 'flutter-shop-mds',
    storageBucket: 'flutter-shop-mds.firebasestorage.app',
    iosClientId: '1068162247377-pgf2ua7ghoiarpvdcc06768afbf3rsi9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterShop',
  );

}